# Generated by Django 4.2.16 on 2024-11-22 10:38

from django.db import migrations, models
import quizapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.TextField()),
                ('phone', models.CharField(help_text='Enter a 10-digit phone number', max_length=10, validators=[quizapp.models.validate_phone_number])),
            ],
        ),
    ]
